// Generated by gencpp from file ddori_msgs/AutoDockingGoal.msg
// DO NOT EDIT!


#ifndef DDORI_MSGS_MESSAGE_AUTODOCKINGGOAL_H
#define DDORI_MSGS_MESSAGE_AUTODOCKINGGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ddori_msgs
{
template <class ContainerAllocator>
struct AutoDockingGoal_
{
  typedef AutoDockingGoal_<ContainerAllocator> Type;

  AutoDockingGoal_()
    {
    }
  AutoDockingGoal_(const ContainerAllocator& _alloc)
    {
    }






  typedef boost::shared_ptr< ::ddori_msgs::AutoDockingGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ddori_msgs::AutoDockingGoal_<ContainerAllocator> const> ConstPtr;

}; // struct AutoDockingGoal_

typedef ::ddori_msgs::AutoDockingGoal_<std::allocator<void> > AutoDockingGoal;

typedef boost::shared_ptr< ::ddori_msgs::AutoDockingGoal > AutoDockingGoalPtr;
typedef boost::shared_ptr< ::ddori_msgs::AutoDockingGoal const> AutoDockingGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ddori_msgs::AutoDockingGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ddori_msgs::AutoDockingGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ddori_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'ddori_msgs': ['/home/dolmangi/catkin_ws/src/ddori_msgs/msg', '/home/dolmangi/catkin_ws/devel/share/ddori_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ddori_msgs::AutoDockingGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ddori_msgs::AutoDockingGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ddori_msgs::AutoDockingGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ddori_msgs::AutoDockingGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ddori_msgs::AutoDockingGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ddori_msgs::AutoDockingGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ddori_msgs::AutoDockingGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::ddori_msgs::AutoDockingGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::ddori_msgs::AutoDockingGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ddori_msgs/AutoDockingGoal";
  }

  static const char* value(const ::ddori_msgs::AutoDockingGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ddori_msgs::AutoDockingGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal\n\
";
  }

  static const char* value(const ::ddori_msgs::AutoDockingGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ddori_msgs::AutoDockingGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct AutoDockingGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ddori_msgs::AutoDockingGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::ddori_msgs::AutoDockingGoal_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // DDORI_MSGS_MESSAGE_AUTODOCKINGGOAL_H
