"""autogenerated by genpy from ddori/motor_speed.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class motor_speed(genpy.Message):
  _md5sum = "621b34f25ac94b760c1ddd9f2c38ce75"
  _type = "ddori/motor_speed"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """
uint8 left_speed
uint8 left_dir
uint8 right_speed
uint8 right_dir

"""
  __slots__ = ['left_speed','left_dir','right_speed','right_dir']
  _slot_types = ['uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       left_speed,left_dir,right_speed,right_dir

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(motor_speed, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.left_speed is None:
        self.left_speed = 0
      if self.left_dir is None:
        self.left_dir = 0
      if self.right_speed is None:
        self.right_speed = 0
      if self.right_dir is None:
        self.right_dir = 0
    else:
      self.left_speed = 0
      self.left_dir = 0
      self.right_speed = 0
      self.right_dir = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4B.pack(_x.left_speed, _x.left_dir, _x.right_speed, _x.right_dir))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.left_speed, _x.left_dir, _x.right_speed, _x.right_dir,) = _struct_4B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4B.pack(_x.left_speed, _x.left_dir, _x.right_speed, _x.right_dir))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.left_speed, _x.left_dir, _x.right_speed, _x.right_dir,) = _struct_4B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4B = struct.Struct("<4B")
