(cl:in-package ddori-msg)
(cl:export '(TIME_STAMP-VAL
          TIME_STAMP
          BUMPER-VAL
          BUMPER
          LEFT_ENCODER-VAL
          LEFT_ENCODER
          RIGHT_ENCODER-VAL
          RIGHT_ENCODER
          BUTTONS-VAL
          BUTTONS
          CHARGER-VAL
          CHARGER
          VOLTAGE-VAL
          VOLTAGE
          CURRENT-VAL
          CURRENT
          TEMP1-VAL
          TEMP1
          TEMP2-VAL
          TEMP2
          TEMP3-VAL
          TEMP3
          CO-VAL
          CO
          GAS-VAL
          GAS
          AIR-VAL
          AIR
          BAROMETER-VAL
          BAROMETER
          PIR-VAL
          PIR
          PRX_1-VAL
          PRX_1
          PRX_2-VAL
          PRX_2
          PRX_3-VAL
          PRX_3
          ALS-VAL
          ALS
))