// Generated by gencpp from file ddori/battery_msg.msg
// DO NOT EDIT!


#ifndef DDORI_MESSAGE_BATTERY_MSG_H
#define DDORI_MESSAGE_BATTERY_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ddori
{
template <class ContainerAllocator>
struct battery_msg_
{
  typedef battery_msg_<ContainerAllocator> Type;

  battery_msg_()
    : voltage(0)
    , current(0)  {
    }
  battery_msg_(const ContainerAllocator& _alloc)
    : voltage(0)
    , current(0)  {
    }



   typedef int16_t _voltage_type;
  _voltage_type voltage;

   typedef int16_t _current_type;
  _current_type current;




  typedef boost::shared_ptr< ::ddori::battery_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ddori::battery_msg_<ContainerAllocator> const> ConstPtr;

}; // struct battery_msg_

typedef ::ddori::battery_msg_<std::allocator<void> > battery_msg;

typedef boost::shared_ptr< ::ddori::battery_msg > battery_msgPtr;
typedef boost::shared_ptr< ::ddori::battery_msg const> battery_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ddori::battery_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ddori::battery_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ddori

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ddori': ['/home/dolmangi/catkin_ws/src/ddori/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ddori::battery_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ddori::battery_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ddori::battery_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ddori::battery_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ddori::battery_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ddori::battery_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ddori::battery_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd3d37c458ffb8eedfe783df816f558b";
  }

  static const char* value(const ::ddori::battery_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd3d37c458ffb8eeULL;
  static const uint64_t static_value2 = 0xdfe783df816f558bULL;
};

template<class ContainerAllocator>
struct DataType< ::ddori::battery_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ddori/battery_msg";
  }

  static const char* value(const ::ddori::battery_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ddori::battery_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 voltage\n\
int16 current\n\
";
  }

  static const char* value(const ::ddori::battery_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ddori::battery_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.voltage);
      stream.next(m.current);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct battery_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ddori::battery_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ddori::battery_msg_<ContainerAllocator>& v)
  {
    s << indent << "voltage: ";
    Printer<int16_t>::stream(s, indent + "  ", v.voltage);
    s << indent << "current: ";
    Printer<int16_t>::stream(s, indent + "  ", v.current);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DDORI_MESSAGE_BATTERY_MSG_H
