// Generated by gencpp from file ddori/motor_speed.msg
// DO NOT EDIT!


#ifndef DDORI_MESSAGE_MOTOR_SPEED_H
#define DDORI_MESSAGE_MOTOR_SPEED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ddori
{
template <class ContainerAllocator>
struct motor_speed_
{
  typedef motor_speed_<ContainerAllocator> Type;

  motor_speed_()
    : left_speed(0)
    , left_dir(0)
    , right_speed(0)
    , right_dir(0)  {
    }
  motor_speed_(const ContainerAllocator& _alloc)
    : left_speed(0)
    , left_dir(0)
    , right_speed(0)
    , right_dir(0)  {
    }



   typedef uint8_t _left_speed_type;
  _left_speed_type left_speed;

   typedef uint8_t _left_dir_type;
  _left_dir_type left_dir;

   typedef uint8_t _right_speed_type;
  _right_speed_type right_speed;

   typedef uint8_t _right_dir_type;
  _right_dir_type right_dir;




  typedef boost::shared_ptr< ::ddori::motor_speed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ddori::motor_speed_<ContainerAllocator> const> ConstPtr;

}; // struct motor_speed_

typedef ::ddori::motor_speed_<std::allocator<void> > motor_speed;

typedef boost::shared_ptr< ::ddori::motor_speed > motor_speedPtr;
typedef boost::shared_ptr< ::ddori::motor_speed const> motor_speedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ddori::motor_speed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ddori::motor_speed_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ddori

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ddori': ['/home/dolmangi/catkin_ws/src/ddori/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ddori::motor_speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ddori::motor_speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ddori::motor_speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ddori::motor_speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ddori::motor_speed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ddori::motor_speed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ddori::motor_speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "621b34f25ac94b760c1ddd9f2c38ce75";
  }

  static const char* value(const ::ddori::motor_speed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x621b34f25ac94b76ULL;
  static const uint64_t static_value2 = 0x0c1ddd9f2c38ce75ULL;
};

template<class ContainerAllocator>
struct DataType< ::ddori::motor_speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ddori/motor_speed";
  }

  static const char* value(const ::ddori::motor_speed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ddori::motor_speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
uint8 left_speed\n\
uint8 left_dir\n\
uint8 right_speed\n\
uint8 right_dir\n\
";
  }

  static const char* value(const ::ddori::motor_speed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ddori::motor_speed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_speed);
      stream.next(m.left_dir);
      stream.next(m.right_speed);
      stream.next(m.right_dir);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct motor_speed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ddori::motor_speed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ddori::motor_speed_<ContainerAllocator>& v)
  {
    s << indent << "left_speed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_speed);
    s << indent << "left_dir: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_dir);
    s << indent << "right_speed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_speed);
    s << indent << "right_dir: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_dir);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DDORI_MESSAGE_MOTOR_SPEED_H
