// Generated by gencpp from file ddori/pir_sensor_msg.msg
// DO NOT EDIT!


#ifndef DDORI_MESSAGE_PIR_SENSOR_MSG_H
#define DDORI_MESSAGE_PIR_SENSOR_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ddori
{
template <class ContainerAllocator>
struct pir_sensor_msg_
{
  typedef pir_sensor_msg_<ContainerAllocator> Type;

  pir_sensor_msg_()
    : pir_det(0)  {
    }
  pir_sensor_msg_(const ContainerAllocator& _alloc)
    : pir_det(0)  {
    }



   typedef int16_t _pir_det_type;
  _pir_det_type pir_det;




  typedef boost::shared_ptr< ::ddori::pir_sensor_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ddori::pir_sensor_msg_<ContainerAllocator> const> ConstPtr;

}; // struct pir_sensor_msg_

typedef ::ddori::pir_sensor_msg_<std::allocator<void> > pir_sensor_msg;

typedef boost::shared_ptr< ::ddori::pir_sensor_msg > pir_sensor_msgPtr;
typedef boost::shared_ptr< ::ddori::pir_sensor_msg const> pir_sensor_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ddori::pir_sensor_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ddori::pir_sensor_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ddori

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ddori': ['/home/dolmangi/catkin_ws/src/ddori/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ddori::pir_sensor_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ddori::pir_sensor_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ddori::pir_sensor_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ddori::pir_sensor_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ddori::pir_sensor_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ddori::pir_sensor_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ddori::pir_sensor_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "93bcdcb8db8db5a0d8f5bbfee92c9470";
  }

  static const char* value(const ::ddori::pir_sensor_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x93bcdcb8db8db5a0ULL;
  static const uint64_t static_value2 = 0xd8f5bbfee92c9470ULL;
};

template<class ContainerAllocator>
struct DataType< ::ddori::pir_sensor_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ddori/pir_sensor_msg";
  }

  static const char* value(const ::ddori::pir_sensor_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ddori::pir_sensor_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 pir_det \n\
";
  }

  static const char* value(const ::ddori::pir_sensor_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ddori::pir_sensor_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pir_det);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct pir_sensor_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ddori::pir_sensor_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ddori::pir_sensor_msg_<ContainerAllocator>& v)
  {
    s << indent << "pir_det: ";
    Printer<int16_t>::stream(s, indent + "  ", v.pir_det);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DDORI_MESSAGE_PIR_SENSOR_MSG_H
