// Generated by gencpp from file ddori/temperature_msg.msg
// DO NOT EDIT!


#ifndef DDORI_MESSAGE_TEMPERATURE_MSG_H
#define DDORI_MESSAGE_TEMPERATURE_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ddori
{
template <class ContainerAllocator>
struct temperature_msg_
{
  typedef temperature_msg_<ContainerAllocator> Type;

  temperature_msg_()
    : temperature_1(0)
    , temperature_2(0)
    , temperature_3(0)  {
    }
  temperature_msg_(const ContainerAllocator& _alloc)
    : temperature_1(0)
    , temperature_2(0)
    , temperature_3(0)  {
    }



   typedef int16_t _temperature_1_type;
  _temperature_1_type temperature_1;

   typedef int16_t _temperature_2_type;
  _temperature_2_type temperature_2;

   typedef int16_t _temperature_3_type;
  _temperature_3_type temperature_3;




  typedef boost::shared_ptr< ::ddori::temperature_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ddori::temperature_msg_<ContainerAllocator> const> ConstPtr;

}; // struct temperature_msg_

typedef ::ddori::temperature_msg_<std::allocator<void> > temperature_msg;

typedef boost::shared_ptr< ::ddori::temperature_msg > temperature_msgPtr;
typedef boost::shared_ptr< ::ddori::temperature_msg const> temperature_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ddori::temperature_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ddori::temperature_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ddori

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ddori': ['/home/dolmangi/catkin_ws/src/ddori/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ddori::temperature_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ddori::temperature_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ddori::temperature_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ddori::temperature_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ddori::temperature_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ddori::temperature_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ddori::temperature_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a517f950068fd79d1237ea6fbcec900";
  }

  static const char* value(const ::ddori::temperature_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a517f950068fd79ULL;
  static const uint64_t static_value2 = 0xd1237ea6fbcec900ULL;
};

template<class ContainerAllocator>
struct DataType< ::ddori::temperature_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ddori/temperature_msg";
  }

  static const char* value(const ::ddori::temperature_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ddori::temperature_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 temperature_1 \n\
int16 temperature_2\n\
int16 temperature_3\n\
";
  }

  static const char* value(const ::ddori::temperature_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ddori::temperature_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.temperature_1);
      stream.next(m.temperature_2);
      stream.next(m.temperature_3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct temperature_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ddori::temperature_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ddori::temperature_msg_<ContainerAllocator>& v)
  {
    s << indent << "temperature_1: ";
    Printer<int16_t>::stream(s, indent + "  ", v.temperature_1);
    s << indent << "temperature_2: ";
    Printer<int16_t>::stream(s, indent + "  ", v.temperature_2);
    s << indent << "temperature_3: ";
    Printer<int16_t>::stream(s, indent + "  ", v.temperature_3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DDORI_MESSAGE_TEMPERATURE_MSG_H
